remote_theme: jekyll/minima@93b192192c0777018c9ac4daadaafd5af5a4f750

title: aldw
author:
  name: alden wu (goodtrailer)
  email: me@aldw.net
  email-work: hireme@aldw.net
repository: goodtrailer/goodtrailer

plugins:
  - jekyll-feed
  - jekyll-paginate
  #- jekyll-redirect-from
  - jekyll-seo-tag

header_pages:
  - index.md
  - projects.md
  - math.md
  - resume.md
  - archive.md
  - about.md
  #- blog/index.html

include:
  - CNAME

paginate: 5
paginate_path: "/blog/page:num/"
show_excerpts: true
permalink: pretty

minima:
  social_links:
    - { platform: email, user_url: "mailto:me@aldw.net", title: "Email (Personal)" }
    - { platform: rss, user_url: "/feed.xml", title: "RSS" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/aldenwu0", title: "LinkedIn" }
    - { platform: github, user_url: "https://github.com/goodtrailer", title: "GitHub" }
    - { platform: youtube, user_url: "https://www.youtube.com/@goodtrailer0", title: "YouTube" }
    - { platform: myanimelist, user_url: "https://myanimelist.net/animelist/goodtrailer?status=7&order=4&order2=0", title: "MyAnimeList" }
    - { platform: osu, user_url: "https://osu.ppy.sh/users/18510196", title: "osu!" }

kramdown:
  math_engine: mathjax
